version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: '10:00'
  open-pull-requests-limit: 10
  reviewers:
  - '@security-team'
  assignees:
  - '@dev-team'
  commit-message:
    prefix: deps
    include: scope
- package-ecosystem: docker
  directory: /deploy
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
