"""AMOSKYS Observability Contract — Probe Audit Engine.

Importable module that validates every probe's Observability Contract.
Used by:
  - scripts/eoa/attribute_audit.py (CLI)
  - web/app/dashboard (probe-health API endpoint)
"""

from __future__ import annotations

import importlib
from typing import Any, Dict, List

# Agent → probe factory mapping
AGENT_PROBE_MAP: Dict[str, Dict[str, str]] = {
    "proc": {
        "module": "amoskys.agents.proc.probes",
        "factory": "create_proc_probes",
    },
    "fim": {
        "module": "amoskys.agents.fim.probes",
        "factory": "create_fim_probes",
    },
    "flow": {
        "module": "amoskys.agents.flow.probes",
        "factory": "create_flow_probes",
    },
    "dns": {
        "module": "amoskys.agents.dns.probes",
        "factory": "create_dns_probes",
    },
    "peripheral": {
        "module": "amoskys.agents.peripheral.probes",
        "factory": "create_peripheral_probes",
    },
    "auth": {
        "module": "amoskys.agents.auth.probes",
        "factory": "create_auth_probes",
    },
    "persistence": {
        "module": "amoskys.agents.persistence.probes",
        "factory": "create_persistence_probes",
    },
    "kernel_audit": {
        "module": "amoskys.agents.kernel_audit.probes",
        "factory": "create_kernel_audit_probes",
    },
    "device_discovery": {
        "module": "amoskys.agents.device_discovery.probes",
        "factory": "create_device_discovery_probes",
    },
    "protocol_collectors": {
        "module": "amoskys.agents.protocol_collectors.probes",
        "factory": "create_protocol_collector_probes",
    },
    # L7 Gap-Closure Agents
    "applog": {
        "module": "amoskys.agents.applog.probes",
        "factory": "create_applog_probes",
    },
    "db_activity": {
        "module": "amoskys.agents.db_activity.probes",
        "factory": "create_db_activity_probes",
    },
    "http_inspector": {
        "module": "amoskys.agents.http_inspector.probes",
        "factory": "create_http_inspector_probes",
    },
    "internet_activity": {
        "module": "amoskys.agents.internet_activity.probes",
        "factory": "create_internet_activity_probes",
    },
    "net_scanner": {
        "module": "amoskys.agents.net_scanner.probes",
        "factory": "create_net_scanner_probes",
    },
}

# Known collector event types per agent
COLLECTOR_EVENT_TYPES: Dict[str, List[str]] = {
    "auth": [
        "SSH_LOGIN_SUCCESS",
        "SSH_LOGIN_FAILURE",
        "SUDO_COMMAND",
        "SUDO_FAILURE",
        "AUTH_PROMPT",
    ],
    "persistence": [
        "USER_LAUNCH_AGENT",
        "SYSTEM_LAUNCH_AGENT",
        "SYSTEM_LAUNCH_DAEMON",
        "CRON_USER",
        "SHELL_PROFILE",
        "SSH_AUTHORIZED_KEYS",
        "BROWSER_EXTENSION",
        "STARTUP_ITEM",
        "HIDDEN_FILE",
    ],
}


def audit_probe(probe: object, agent_name: str, target_platform: str) -> Dict[str, Any]:
    """Audit a single probe's Observability Contract."""
    name = getattr(probe, "name", "unknown")
    platforms = getattr(probe, "platforms", ["linux", "darwin", "windows"])
    requires_fields = getattr(probe, "requires_fields", None)
    requires_event_types = getattr(probe, "requires_event_types", [])
    field_semantics = getattr(probe, "field_semantics", {})
    degraded_without = getattr(probe, "degraded_without", [])

    result: Dict[str, Any] = {
        "probe": name,
        "agent": agent_name,
        "platforms": platforms,
        "requires_fields": requires_fields if requires_fields is not None else [],
        "requires_event_types": requires_event_types,
        "field_semantics": field_semantics,
        "degraded_without": degraded_without,
        "issues": [],
        "verdict": "REAL",
    }

    # Check 1: Platform support
    if target_platform and target_platform not in platforms:
        result["verdict"] = "DISABLED"
        result["issues"].append(f"Platform {target_platform} not supported")
        return result

    # Check 2: Contract declaration exists
    if requires_fields is None:
        result["verdict"] = "UNDECLARED"
        result["issues"].append("No requires_fields declared")
        return result

    # Check 3: Event type requirements satisfiable
    collector_events = set(COLLECTOR_EVENT_TYPES.get(agent_name, []))
    for evt_type in requires_event_types:
        if collector_events and evt_type not in collector_events:
            result["verdict"] = "BROKEN"
            result["issues"].append(f"Event type {evt_type} not generated by collector")

    # Check 4: Field semantics documented
    if requires_fields and not field_semantics:
        result["issues"].append("No field_semantics documented")

    # Check 5: Degraded fields
    if degraded_without:
        if result["verdict"] == "REAL":
            result["verdict"] = "DEGRADED"
            result["issues"].append(f"Degraded without: {', '.join(degraded_without)}")

    return result


def run_audit(target_platform: str = "") -> List[Dict[str, Any]]:
    """Run the full attribute audit across all agents."""
    results = []

    for agent_name, info in AGENT_PROBE_MAP.items():
        try:
            mod = importlib.import_module(info["module"])
            factory = getattr(mod, info["factory"])
            probes = factory()

            for probe in probes:
                result = audit_probe(probe, agent_name, target_platform)
                results.append(result)

        except Exception as e:
            results.append(
                {
                    "probe": "IMPORT_ERROR",
                    "agent": agent_name,
                    "verdict": "ERROR",
                    "issues": [str(e)],
                }
            )

    return results


def summarize_audit(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Produce a summary dict suitable for API responses."""
    by_verdict: Dict[str, int] = {}
    by_agent: Dict[str, Dict[str, Any]] = {}

    for r in results:
        verdict = r["verdict"]
        agent = r.get("agent", "unknown")

        by_verdict[verdict] = by_verdict.get(verdict, 0) + 1

        if agent not in by_agent:
            by_agent[agent] = {
                "total": 0,
                "REAL": 0,
                "DEGRADED": 0,
                "BROKEN": 0,
                "DISABLED": 0,
            }
        by_agent[agent]["total"] += 1
        if verdict in by_agent[agent]:
            by_agent[agent][verdict] += 1

    return {
        "total": len(results),
        "real": by_verdict.get("REAL", 0),
        "degraded": by_verdict.get("DEGRADED", 0),
        "broken": by_verdict.get("BROKEN", 0),
        "disabled": by_verdict.get("DISABLED", 0),
        "error": by_verdict.get("ERROR", 0),
        "by_agent": by_agent,
    }


def print_table(results: List[Dict[str, Any]]) -> None:
    """Print a human-readable audit table."""
    by_verdict: Dict[str, List[Dict[str, Any]]] = {}
    for r in results:
        by_verdict.setdefault(r["verdict"], []).append(r)

    total = len(results)
    print()
    print("=" * 70)
    print(" AMOSKYS Attribute Audit \u2014 Observability Contract Report")
    print("=" * 70)
    print()

    for verdict in ["REAL", "DEGRADED", "BROKEN", "DISABLED", "UNDECLARED", "ERROR"]:
        probes = by_verdict.get(verdict, [])
        if not probes:
            continue

        icon = {
            "REAL": "+",
            "DEGRADED": "~",
            "BROKEN": "!",
            "DISABLED": "-",
            "UNDECLARED": "?",
            "ERROR": "X",
        }.get(verdict, " ")

        print(f"  [{icon}] {verdict}: {len(probes)} probes")
        for p in probes:
            issues = "; ".join(p.get("issues", []))
            suffix = f" \u2014 {issues}" if issues else ""
            print(f"      {p['agent']:15s} {p['probe']}{suffix}")
        print()

    real = len(by_verdict.get("REAL", []))
    degraded = len(by_verdict.get("DEGRADED", []))
    broken = len(by_verdict.get("BROKEN", []))
    disabled = len(by_verdict.get("DISABLED", []))
    active = real + degraded

    print("-" * 70)
    print(f"  TOTAL: {total} probes")
    print(
        f"  ACTIVE: {active} ({100 * active / total:.1f}%)" if total else "  ACTIVE: 0"
    )
    print(
        f"  REAL: {real}  DEGRADED: {degraded}  BROKEN: {broken}  DISABLED: {disabled}"
    )
    print("=" * 70)
    print()
