# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from amoskys.proto import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventBusControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishSignal = channel.unary_unary(
                '/messaging.EventBusControl/PublishSignal',
                request_serializer=control__pb2.AgentSignal.SerializeToString,
                response_deserializer=control__pb2.SignalAck.FromString,
                _registered_method=True)
        self.SubscribeSignals = channel.unary_stream(
                '/messaging.EventBusControl/SubscribeSignals',
                request_serializer=control__pb2.SignalSubscribe.SerializeToString,
                response_deserializer=control__pb2.AgentSignal.FromString,
                _registered_method=True)


class EventBusControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSignal,
                    request_deserializer=control__pb2.AgentSignal.FromString,
                    response_serializer=control__pb2.SignalAck.SerializeToString,
            ),
            'SubscribeSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSignals,
                    request_deserializer=control__pb2.SignalSubscribe.FromString,
                    response_serializer=control__pb2.AgentSignal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messaging.EventBusControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messaging.EventBusControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBusControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messaging.EventBusControl/PublishSignal',
            control__pb2.AgentSignal.SerializeToString,
            control__pb2.SignalAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/messaging.EventBusControl/SubscribeSignals',
            control__pb2.SignalSubscribe.SerializeToString,
            control__pb2.AgentSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
