# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\tmessaging\"m\n\x0b\x41gentSignal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x14\n\x0cpayload_json\x18\x05 \x01(\t\x12\r\n\x05ts_ns\x18\x06 \x01(\x04\"3\n\x0fSignalSubscribe\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06topics\x18\x02 \x03(\t\"-\n\tSignalAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x9a\x01\n\x0f\x45ventBusControl\x12=\n\rPublishSignal\x12\x16.messaging.AgentSignal\x1a\x14.messaging.SignalAck\x12H\n\x10SubscribeSignals\x12\x1a.messaging.SignalSubscribe\x1a\x16.messaging.AgentSignal0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSIGNAL']._serialized_start=28
  _globals['_AGENTSIGNAL']._serialized_end=137
  _globals['_SIGNALSUBSCRIBE']._serialized_start=139
  _globals['_SIGNALSUBSCRIBE']._serialized_end=190
  _globals['_SIGNALACK']._serialized_start=192
  _globals['_SIGNALACK']._serialized_end=237
  _globals['_EVENTBUSCONTROL']._serialized_start=240
  _globals['_EVENTBUSCONTROL']._serialized_end=394
# @@protoc_insertion_point(module_scope)
