"""
AMOSKYS Common Utilities

Shared utilities used across all AMOSKYS components including:
- Unified exception hierarchy
- Structured logging infrastructure
- Cryptographic utilities
"""

from .exceptions import (  # Base classes
    AgentConnectionError,
    AgentError,
    AgentNotFoundError,
    AgentOfflineError,
    AmoskysError,
    AuthenticationError,
    AuthorizationError,
    ConfigurationError,
    ConfigurationMissingError,
    ConnectionTimeoutError,
    DatabaseConnectionError,
    DatabaseError,
    DetectionPipelineError,
    DuplicateValueError,
    ErrorCode,
    InternalError,
    InvalidFormatError,
    MFARequiredError,
    MissingFieldError,
    NotImplementedError,
    RateLimitExceededError,
    ResourceConflictError,
    ResourceForbiddenError,
    ResourceNotFoundError,
    RuleParseError,
    ServiceUnavailableError,
    TokenExpiredError,
    TokenInvalidError,
    ValidationError,
    wrap_exception,
)
from .logging import (
    JSONFormatter,
    StructuredLogger,
    clear_request_context,
    configure_logging,
    filter_sensitive_data,
    generate_correlation_id,
    get_correlation_id,
    get_logger,
    get_request_context,
    init_flask_logging,
    log_call,
    log_exceptions,
    set_correlation_id,
    set_request_context,
    update_request_context,
)

__all__ = [
    # Exceptions
    "AmoskysError",
    "ErrorCode",
    "AuthenticationError",
    "TokenExpiredError",
    "TokenInvalidError",
    "MFARequiredError",
    "AuthorizationError",
    "ResourceForbiddenError",
    "ValidationError",
    "MissingFieldError",
    "InvalidFormatError",
    "DuplicateValueError",
    "AgentError",
    "AgentNotFoundError",
    "AgentOfflineError",
    "AgentConnectionError",
    "ConnectionTimeoutError",
    "DetectionPipelineError",
    "RuleParseError",
    "ResourceNotFoundError",
    "ResourceConflictError",
    "RateLimitExceededError",
    "DatabaseError",
    "DatabaseConnectionError",
    "ConfigurationError",
    "ConfigurationMissingError",
    "InternalError",
    "NotImplementedError",
    "ServiceUnavailableError",
    "wrap_exception",
    # Logging
    "get_logger",
    "configure_logging",
    "generate_correlation_id",
    "get_correlation_id",
    "set_correlation_id",
    "get_request_context",
    "set_request_context",
    "update_request_context",
    "clear_request_context",
    "filter_sensitive_data",
    "init_flask_logging",
    "StructuredLogger",
    "JSONFormatter",
    "log_call",
    "log_exceptions",
]
