# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messaging_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16messaging_schema.proto\x12\tmessaging\"\x99\x01\n\x0cProcessEvent\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0c\n\x04ppid\x18\x02 \x01(\x04\x12\x0b\n\x03\x65xe\x18\x03 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x04 \x03(\t\x12\x13\n\x0bstart_ts_ns\x18\x05 \x01(\x04\x12\x0b\n\x03uid\x18\x06 \x01(\r\x12\x0b\n\x03gid\x18\x07 \x01(\r\x12\x0e\n\x06\x63group\x18\x08 \x01(\t\x12\x14\n\x0c\x63ontainer_id\x18\t \x01(\t\"\x86\x02\n\tFlowEvent\x12\x0e\n\x06src_ip\x18\x01 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x10\n\x08src_port\x18\x03 \x01(\r\x12\x10\n\x08\x64st_port\x18\x04 \x01(\r\x12\x10\n\x08protocol\x18\x05 \x01(\t\x12\x12\n\nbytes_sent\x18\x06 \x01(\x04\x12\x12\n\nbytes_recv\x18\x07 \x01(\x04\x12\r\n\x05\x66lags\x18\x08 \x01(\r\x12\x12\n\nstart_time\x18\t \x01(\x04\x12\x10\n\x08\x65nd_time\x18\n \x01(\x04\x12\x10\n\x08\x62ytes_tx\x18\x0b \x01(\x04\x12\x10\n\x08\x62ytes_rx\x18\x0c \x01(\x04\x12\r\n\x05proto\x18\r \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x0e \x01(\r\"\x97\x01\n\x08\x45nvelope\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05ts_ns\x18\x02 \x01(\x04\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\x12\"\n\x04\x66low\x18\x04 \x01(\x0b\x32\x14.messaging.FlowEvent\x12\x0b\n\x03sig\x18\x05 \x01(\x0c\x12\x10\n\x08prev_sig\x18\x06 \x01(\x0c\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\"\x9f\x01\n\nPublishAck\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.messaging.PublishAck.Status\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61\x63koff_hint_ms\x18\x03 \x01(\x05\":\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05RETRY\x10\x01\x12\x0b\n\x07INVALID\x10\x02\x12\x10\n\x0cUNAUTHORIZED\x10\x03\x32\x41\n\x08\x45ventBus\x12\x35\n\x07Publish\x12\x13.messaging.Envelope\x1a\x15.messaging.PublishAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSEVENT']._serialized_start=38
  _globals['_PROCESSEVENT']._serialized_end=191
  _globals['_FLOWEVENT']._serialized_start=194
  _globals['_FLOWEVENT']._serialized_end=456
  _globals['_ENVELOPE']._serialized_start=459
  _globals['_ENVELOPE']._serialized_end=610
  _globals['_PUBLISHACK']._serialized_start=613
  _globals['_PUBLISHACK']._serialized_end=772
  _globals['_PUBLISHACK_STATUS']._serialized_start=714
  _globals['_PUBLISHACK_STATUS']._serialized_end=772
  _globals['_EVENTBUS']._serialized_start=774
  _globals['_EVENTBUS']._serialized_end=839
# @@protoc_insertion_point(module_scope)
